"""create despesas table

Revision ID: f70b787ed180
Revises: 16b9ba954471
Create Date: 2026-01-19 20:22:38.272191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f70b787ed180'
down_revision: Union[str, Sequence[str], None] = '16b9ba954471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesas',
    sa.Column('id', sa.INTEGER(), primary_key=True, autoincrement=True),
    sa.Column('idDocumento', sa.INTEGER(), index=True),
    sa.Column('mes', sa.INTEGER(), index=True),
    sa.Column('ano', sa.INTEGER(), index=True),
    sa.Column('codigoLegislatura', sa.INTEGER(), index=True),
    sa.Column('nomeParlamentar', sa.VARCHAR()),
    sa.Column('idDeputado', sa.INTEGER(), index=True),
    sa.Column('descricao', sa.VARCHAR()),
    sa.Column('fornecedor', sa.VARCHAR()),
    sa.Column('dataEmissao', sa.DATE()),
    sa.Column('valorDocumento', sa.FLOAT()),
    sa.Column('valorGlosa', sa.FLOAT()),
    sa.Column('valorLiquido', sa.FLOAT()),
    sa.Column('restituicao', sa.FLOAT()),
    sa.Column('datPagamentoRestituicao', sa.DATE()),
    sa.Column('tipoDocumento', sa.INTEGER()),
    sa.Column('urlDocumento', sa.VARCHAR()),

    sa.Column('passageiro', sa.VARCHAR()),
    sa.Column('trecho', sa.VARCHAR()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('despesas')
    # ### end Alembic commands ###
